Default: &defaults
  database: TestTemplating.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: TestTemplating_test.sqlite3
  <<: *defaults

Staging:
  database: TestTemplating_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: TestTemplating_production.sqlite3
  poolsize: 100
  <<: *defaults
